[package]
name = "dcmfx_fuzz"
edition = "2024"

[dependencies]
afl = "0.17.0"
dcmfx = { path = "../dcmfx" }
image = { version = "0.25.6", default-features = false, features = [
  "jpeg",
  "png",
] }
