[package]
name = "dicom_read_pixel_data"
edition.workspace = true
rust-version.workspace = true

[dependencies]
dcmfx = { path = "../../../src/rust/dcmfx" }
image = { version = "0.25.9", default-features = false, features = ["png"] }
