name = "dcmfx_anonymize"
version = "0.41.1"
description = "DCMfx anonymize library"
licences = ["AGPL-3.0-only"]
gleam = ">= 1.14.0"

[repository]
type = "github"
user = "dcmfx"
repo = "dcmfx"
path = "src/gleam/dcmfx_anonymize"

[dependencies]
dcmfx_core = { path = "../dcmfx_core" }
gleam_stdlib = ">= 0.65.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.6.1 and < 2.0.0"

[javascript]
typescript_declarations = true
deno = { allow_read = true }
